// <auto-generated />
using System;
using CodeFirst3.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CodeFirst3.Migrations
{
    [DbContext(typeof(MyDbContext))]
    partial class MyDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CodeFirst3.Models.AppUser", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            CreatedDate = new DateTime(2024, 7, 15, 13, 9, 25, 635, DateTimeKind.Local).AddTicks(7126),
                            ModifiedDate = new DateTime(2024, 7, 15, 13, 9, 25, 635, DateTimeKind.Local).AddTicks(7150),
                            Password = "$2a$11$Y0u31yvS4U1.YAoVLKmpeumdR2tin8ug9Ve6JmSeYGwdYhLY8lFT.",
                            Role = 1,
                            Status = 1,
                            UserName = "administrator"
                        },
                        new
                        {
                            ID = 2,
                            CreatedDate = new DateTime(2024, 7, 15, 13, 9, 25, 635, DateTimeKind.Local).AddTicks(7346),
                            ModifiedDate = new DateTime(2024, 7, 15, 13, 9, 25, 635, DateTimeKind.Local).AddTicks(7347),
                            Password = "$2a$11$g4c7p2bkAE60LYQl8aALf.28GDWIXZIbbHXU89taHCS8v.55RtLK6",
                            Role = 2,
                            Status = 1,
                            UserName = "abdullah"
                        });
                });

            modelBuilder.Entity("CodeFirst3.Models.Author", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("İsim");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Soyisim");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("Yazarlar");
                });

            modelBuilder.Entity("CodeFirst3.Models.Book", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AuthorID")
                        .HasColumnType("int");

                    b.Property<int>("BookTypeID")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PageCount")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("AuthorID");

                    b.HasIndex("BookTypeID");

                    b.ToTable("Books");
                });

            modelBuilder.Entity("CodeFirst3.Models.BookType", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("BookTypes");
                });

            modelBuilder.Entity("CodeFirst3.Models.Operation", b =>
                {
                    b.Property<int>("StudentID")
                        .HasColumnType("int");

                    b.Property<int>("BookID")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("StudentID", "BookID");

                    b.HasIndex("BookID");

                    b.ToTable("Operasyonlar");
                });

            modelBuilder.Entity("CodeFirst3.Models.Student", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("varchar(30)");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            CreatedDate = new DateTime(2024, 7, 15, 13, 9, 25, 636, DateTimeKind.Local).AddTicks(6237),
                            FirstName = "Emirhan",
                            Gender = 1,
                            LastName = "Yeşil",
                            ModifiedDate = new DateTime(2024, 7, 15, 13, 9, 25, 636, DateTimeKind.Local).AddTicks(6242),
                            Status = 1
                        },
                        new
                        {
                            ID = 2,
                            CreatedDate = new DateTime(2024, 7, 15, 13, 9, 25, 636, DateTimeKind.Local).AddTicks(6246),
                            FirstName = "Safa",
                            Gender = 1,
                            LastName = "Başdemir",
                            ModifiedDate = new DateTime(2024, 7, 15, 13, 9, 25, 636, DateTimeKind.Local).AddTicks(6247),
                            Status = 1
                        },
                        new
                        {
                            ID = 3,
                            CreatedDate = new DateTime(2024, 7, 15, 13, 9, 25, 636, DateTimeKind.Local).AddTicks(6250),
                            FirstName = "Gürkan",
                            Gender = 1,
                            LastName = "Taş",
                            ModifiedDate = new DateTime(2024, 7, 15, 13, 9, 25, 636, DateTimeKind.Local).AddTicks(6250),
                            Status = 1
                        },
                        new
                        {
                            ID = 4,
                            CreatedDate = new DateTime(2024, 7, 15, 13, 9, 25, 636, DateTimeKind.Local).AddTicks(6252),
                            FirstName = "Zeynep",
                            Gender = 2,
                            LastName = "Kurt",
                            ModifiedDate = new DateTime(2024, 7, 15, 13, 9, 25, 636, DateTimeKind.Local).AddTicks(6253),
                            Status = 1
                        });
                });

            modelBuilder.Entity("CodeFirst3.Models.StudentDetail", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("BirthDay")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SchoolNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("StudentID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("StudentID")
                        .IsUnique();

                    b.ToTable("StudentDetail");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            BirthDay = new DateTime(1997, 11, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedDate = new DateTime(2024, 7, 15, 13, 9, 25, 636, DateTimeKind.Local).AddTicks(7674),
                            ModifiedDate = new DateTime(2024, 7, 15, 13, 9, 25, 636, DateTimeKind.Local).AddTicks(7677),
                            SchoolNumber = "100",
                            Status = 1,
                            StudentID = 1
                        },
                        new
                        {
                            ID = 2,
                            BirthDay = new DateTime(1997, 11, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedDate = new DateTime(2024, 7, 15, 13, 9, 25, 636, DateTimeKind.Local).AddTicks(7682),
                            ModifiedDate = new DateTime(2024, 7, 15, 13, 9, 25, 636, DateTimeKind.Local).AddTicks(7683),
                            SchoolNumber = "101",
                            Status = 1,
                            StudentID = 2
                        },
                        new
                        {
                            ID = 3,
                            BirthDay = new DateTime(1992, 11, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedDate = new DateTime(2024, 7, 15, 13, 9, 25, 636, DateTimeKind.Local).AddTicks(7686),
                            ModifiedDate = new DateTime(2024, 7, 15, 13, 9, 25, 636, DateTimeKind.Local).AddTicks(7687),
                            SchoolNumber = "102",
                            Status = 1,
                            StudentID = 3
                        },
                        new
                        {
                            ID = 4,
                            BirthDay = new DateTime(1990, 11, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedDate = new DateTime(2024, 7, 15, 13, 9, 25, 636, DateTimeKind.Local).AddTicks(7689),
                            ModifiedDate = new DateTime(2024, 7, 15, 13, 9, 25, 636, DateTimeKind.Local).AddTicks(7696),
                            SchoolNumber = "103",
                            Status = 1,
                            StudentID = 4
                        });
                });

            modelBuilder.Entity("CodeFirst3.Models.Book", b =>
                {
                    b.HasOne("CodeFirst3.Models.Author", "Author")
                        .WithMany("Books")
                        .HasForeignKey("AuthorID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CodeFirst3.Models.BookType", "BookType")
                        .WithMany("Books")
                        .HasForeignKey("BookTypeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("BookType");
                });

            modelBuilder.Entity("CodeFirst3.Models.Operation", b =>
                {
                    b.HasOne("CodeFirst3.Models.Book", "Book")
                        .WithMany("Operations")
                        .HasForeignKey("BookID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CodeFirst3.Models.Student", "Student")
                        .WithMany("Operations")
                        .HasForeignKey("StudentID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("CodeFirst3.Models.StudentDetail", b =>
                {
                    b.HasOne("CodeFirst3.Models.Student", "Student")
                        .WithOne("StudentDetail")
                        .HasForeignKey("CodeFirst3.Models.StudentDetail", "StudentID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");
                });

            modelBuilder.Entity("CodeFirst3.Models.Author", b =>
                {
                    b.Navigation("Books");
                });

            modelBuilder.Entity("CodeFirst3.Models.Book", b =>
                {
                    b.Navigation("Operations");
                });

            modelBuilder.Entity("CodeFirst3.Models.BookType", b =>
                {
                    b.Navigation("Books");
                });

            modelBuilder.Entity("CodeFirst3.Models.Student", b =>
                {
                    b.Navigation("Operations");

                    b.Navigation("StudentDetail");
                });
#pragma warning restore 612, 618
        }
    }
}
